### ISSUE TITLE
Error after download complete

### ISSUE THREAD

**Issue by asdptkt** [josephlewis42/logstash-input-google_cloud_storage#2]
```
logstash_1       | [2019-02-15T10:05:46,463][ERROR][logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.
logstash_1       |   Pipeline_id:main
logstash_1       |   Plugin: <LogStash::Inputs::GoogleCloudStorage json_key_file=>"/usr/share/logstash/x.json", bucket_id=>"my-cf-storage", codec=><LogStash::Codecs::JSONLines id=>"json_lines_92cd009f-4014-41a0-aca0-e933b293a730", enable_metric=>true, charset=>"UTF-8", delimiter=>"\n">, interval=>300, id=>"ccbfb056ac26a89e0c933c13b76bee4b00466ee76629da0cbe556e22a35aead2", file_matches=>"\\w+/\\w+\\.log\\.gz", enable_metric=>true, file_exclude=>"^$", metadata_key=>"x-goog-meta-ls-gcs-input", delete=>false, unpack_gzip=>true, temp_directory=>"/tmp/ls-in-gcs">
logstash_1       |   Error: invalid byte sequence in UTF-8
logstash_1       |   Exception: ArgumentError
logstash_1       |   Stack: org/jruby/RubyString.java:3523:in `split'
logstash_1       | org/logstash/common/BufferedTokenizerExt.java:55:in `extract'
logstash_1       | /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-json_lines-3.0.6/lib/logstash/codecs/json_lines.rb:40:in `decode'
logstash_1       | /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_cloud_storage-0.9.0-java/lib/logstash/inputs/google_cloud_storage.rb:124:in `extract_event'
logstash_1       | /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_cloud_storage-0.9.0-java/lib/logstash/inputs/google_cloud_storage.rb:110:in `block in download_and_process'
logstash_1       | /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_cloud_storage-0.9.0-java/lib/logstash/inputs/cloud_storage/file_reader.rb:44:in `block in read_plain_lines'
logstash_1       | org/jruby/RubyIO.java:3290:in `each'
logstash_1       | /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_cloud_storage-0.9.0-java/lib/logstash/inputs/cloud_storage/file_reader.rb:43:in `read_plain_lines'
logstash_1       | /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_cloud_storage-0.9.0-java/lib/logstash/inputs/cloud_storage/file_reader.rb:32:in `read_lines'
logstash_1       | /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_cloud_storage-0.9.0-java/lib/logstash/inputs/google_cloud_storage.rb:109:in `block in download_and_process'
logstash_1       | /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_cloud_storage-0.9.0-java/lib/logstash/inputs/cloud_storage/blob_adapter.rb:85:in `with_downloaded'
logstash_1       | /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_cloud_storage-0.9.0-java/lib/logstash/inputs/google_cloud_storage.rb:106:in `download_and_process'
logstash_1       | /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_cloud_storage-0.9.0-java/lib/logstash/inputs/google_cloud_storage.rb:83:in `block in list_download_process'
logstash_1       | /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_cloud_storage-0.9.0-java/lib/logstash/inputs/google_cloud_storage.rb:99:in `block in list_processable_blobs'
logstash_1       | /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_cloud_storage-0.9.0-java/lib/logstash/inputs/cloud_storage/client.rb:36:in `block in list_blobs'
logstash_1       | /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_cloud_storage-0.9.0-java/lib/logstash/inputs/cloud_storage/client.rb:35:in `list_blobs'
logstash_1       | /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_cloud_storage-0.9.0-java/lib/logstash/inputs/google_cloud_storage.rb:98:in `list_processable_blobs'
logstash_1       | /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_cloud_storage-0.9.0-java/lib/logstash/inputs/google_cloud_storage.rb:81:in `list_download_process'
logstash_1       | /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_cloud_storage-0.9.0-java/lib/logstash/inputs/google_cloud_storage.rb:74:in `block in run'
logstash_1       | /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/interval.rb:20:in `interval'
logstash_1       | /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_cloud_storage-0.9.0-java/lib/logstash/inputs/google_cloud_storage.rb:73:in `run'
logstash_1       | /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:409:in `inputworker'
logstash_1       | /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:403:in `block in start_input'
```

Hi, I got this error while trying to use your plugin to read Cloudflare's log files. They put the name *.*.log.gz to the bucket but the actual file type is JSON text file.

I've tried setting up `unpack_gzip` to `false` and use `json_lines` codec to no avail. Am I misconfigure it or is it a bug? Thank you.

```
input {
 google_cloud_storage {
   interval => 300
   bucket_id => "my-cf-storage"
   json_key_file => "/usr/share/logstash/x.json"
   file_matches => "\w+/\w+\.log\.gz"
   unpack_gzip => false
   codec => "json_lines"
 }
}

output {
 stdout {
   codec => rubydebug
 }
}
```

**Comment by josephlewis42** [comment]
Hi @asdptkt,

My apologies for the delay.

One odd thing I see is that in your logs the plugin is showing `unpack_gzip` to be true when your config is showing it to be false. Otherwise, things should be working. The plugin will try to unzip the data if the flag is set and the file ends in .gz, otherwise it'll read the lines from the matching files in the bucket.

You might also run into a bug where the line endings were being stripped which makes certain codecs unhappy. That should be fixed in an upcoming version that Elastic is currently reviewing for merge.

Let me know if/how that works for you.

\- Joseph
